### ISSUE TITLE
Something requests user location

### ISSUE THREAD

**Issue by jpakkane** [hotdoc/hotdoc#207] opened 2020-08-18 20:24 UTC
We got the following report:

    Hey, I wanted to quickly pop in and report that the mesonbuild.com website requests the user's location, this seems like an extremely dickish  thing to do, and I cannot think of any sensible reason to request that permission
    This happens even with third-party scripts blocked, so I assume some rogue library snuck in

Meson's web site is fully generated with Hotdoc as installed with Pip. AFAICT we don't do any geo-optimization so it should not need the location info.

**Comment by mateon1** [comment] 2020-08-18 21:04
Hello, I was the one who reported the issue on IRC, but I can't reproduce it again.
I came to the mesonbuild.com site via a Google search result, in Chrome (Chromium 80.0.3987.116), and got the Location API permission popup, asking me whether to allow or disallow the site from accessing the location API.
I clicked 'Block', and reported the above quote on IRC, then came back to the website and tried to reproduce the issue with devtools open (trying to catch a useful network trace). I could not reproduce it despite hard refreshing, clearing caches, resetting the location API permission to "Always Ask" again, and even checking in a different browser.
If I grep through the network captures I don't see any mentions of the geolocation API.

So far I've excluded: HTTP MITM (never touched unencrypted HTTP), my extensions interfering (no external requests, content scripts don't touch location APIs), cookies changing website behavior, devtools changing website behavior, HTTPS MITM (certificate checks out), and some others.
It feels like I encountered one of those rare bitflips in practice, because I honestly have no idea what could have caused something like this.

**Comment by MathieuDuponchelle** [comment] 2020-08-18 23:04
There is definitely nothing in hotdoc's javascript code that would ever require a location, this much I can guarantee. The generated documentation relies on a few javascript libraries, which you can find a summary of in a README in the build directory since https://github.com/hotdoc/hotdoc/commit/194f05d30630fc5eda53844281393ac84880c3f9 . While I haven't reviewed the code for that handful of libraries, I would find it weird and indeed disturbing that one of them would ask for a location.

Considering you cannot reproduce and no one has ever reported such a problem, my first guess would be that for some reason you didn't actually connect to mesonbuild.com but to some other similarly named website and I'll close this issue, please don't hesitate to reopen if you figure out how to reproduce.

**Closed by MathieuDuponchelle** 2020-08-18 23:04 UTC
