### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Volker-Weissmann** [hotdoc/hotdoc#216] opened 2021-01-20 09:34 UTC
Hello,

pip install hotdoc fails on a clean Arch Linux machine:

```
# pip install hotdocCollecting hotdoc
  Using cached hotdoc-0.12.2.tar.gz (1.8 MB)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.4-cp39-cp39-manylinux1_x86_64.whl (629 kB)
     |████████████████████████████████| 629 kB 2.6 MB/s 
Collecting lxml
  Downloading lxml-4.6.2-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 5.1 MB/s 
Collecting schema
  Downloading schema-0.7.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: appdirs in /usr/lib/python3.9/site-packages (from hotdoc) (1.4.4)
Collecting wheezy.template==0.1.167
  Downloading wheezy.template-0.1.167.tar.gz (15 kB)
Collecting toposort>=1.4
  Downloading toposort-1.6-py2.py3-none-any.whl (9.5 kB)
Collecting xdg>=4.0.0
  Downloading xdg-5.0.1-py3-none-any.whl (4.5 kB)
Collecting dbus-deviation>=0.4.0
  Downloading dbus-deviation-0.6.0.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 3.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5v0pufae/dbus-deviation/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5v0pufae/dbus-deviation/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mfg6h_fi
         cwd: /tmp/pip-install-5v0pufae/dbus-deviation/
    Complete output (45 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-t_egrrww/setuptools-pep8/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-t_egrrww/setuptools-pep8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y_oz541x
           cwd: /tmp/pip-wheel-t_egrrww/setuptools-pep8/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for setuptools-pep8
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 119, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8d9kdlu9', '--quiet', 'setuptools_pep8']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5v0pufae/dbus-deviation/setup.py", line 87, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 684, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 743, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 121, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp8d9kdlu9', '--quiet', 'setuptools_pep8']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

`pip install wheel` makes this problem go away. (And installation now fails with https://github.com/pwithnall/dbus-deviation/issues/18)
It seems like you are missed to list wheel as a dependency.

**Comment by MathieuDuponchelle** [comment] 2021-01-20 17:44
that doesn't look like a bug that needs solving at the hotdoc level, as you can see the problem is triggered when building a lower-level dependency. Can you try and build both https://github.com/pwithnall/dbus-deviation/ and https://github.com/CraigJPerry/setuptools-pep8 without the wheel package installed and see if you reproduce?

**Comment by Volker-Weissmann** [comment] 2021-01-20 20:48
After 
$ pip uninstall wheel
, 
$ pip install pep8
works fine, but
$ pip install dbus-deviation
fails like that:

```
[root@root /]# pip install dbus-deviation
Collecting dbus-deviation
  Using cached dbus-deviation-0.6.0.tar.gz (59 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uxjqvqhf/dbus-deviation/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uxjqvqhf/dbus-deviation/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ssr0o8xl
         cwd: /tmp/pip-install-uxjqvqhf/dbus-deviation/
    Complete output (45 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-hicnx1s8/setuptools-pep8/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-hicnx1s8/setuptools-pep8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w3s6zf2t
           cwd: /tmp/pip-wheel-hicnx1s8/setuptools-pep8/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for setuptools-pep8
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 119, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpkl7kbufl', '--quiet', 'setuptools_pep8']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uxjqvqhf/dbus-deviation/setup.py", line 87, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 684, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 743, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 121, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpkl7kbufl', '--quiet', 'setuptools_pep8']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[root@root /]#
```

**Comment by MathieuDuponchelle** [comment] 2021-01-21 00:13
I was not asking about `pip install pep8` but `pip install setuptools-pep8` :) Anyhow, it looks like you have reproduced at least in dbus-deviation, closing this issue, thanks for the report :)

**Closed by MathieuDuponchelle** 2021-01-21 00:13 UTC
