### ISSUE TITLE
gtk-doc-bad-link warning when building with hotdoc

### ISSUE THREAD

**Issue by Thread974** [hotdoc/hotdoc#75] opened 2016-11-14 16:33 UTC
I'm facing the following warning while using hotdoc in my project:
```
WARNING: [core]: (gtk-doc-bad-link): /home/user/Documents/request.c:229:49: Trying to 
               link to non-existing symbol ‘TrpSymbol’
```
However the documentation page for the target symbol TrpSymbol was generated.
The referrer page is built fine with only links to that type missing.

**Comment by Thread974** [comment] 2016-11-14 18:39
Hi, I have hotdoc 0.8.1 in Apertis SDK 16.12. It can be reproduced as follow
```
git clone https://git.apertis.org/git/traprain.git/
make
```
You'll already get a bunch of warnings, and then 
```
touch traprain-common/routing-request.*
make
```
Will take you to the exact error I see. Note the warning didn't appear at first build.

**Comment by Thread974** [comment] 2016-11-14 18:44
And here is imho the relevant part of 
```
set -e ; /usr/bin/hotdoc --project-name Traprain --project-version 0 --index ./docs/reference/markdown_files/index.markdown --output ./docs/reference/built_doc --sitemap ./docs/reference/sitemap.txt --c-sources ./traprain-service/navigation-guidance-progress.c ./traprain-service/navigation.c ./traprain-service/route.c ./traprain-service/turn-by-turn-notification.c ./traprain-service/navigation-guidance-progress.h ./traprain-service/navigation.h ./traprain-service/turn-by-turn-notification.h ./traprain-client/navigation-guidance-progress.c ./traprain-client/navigation.c ./traprain-client/route.c ./traprain-client/mock.c ./traprain-client/navigation-guidance-progress.h ./traprain-client/navigation.h ./traprain-client/route.h ./traprain-client/mock.h ./traprain-common/glib-derived.c ./traprain-common/languages-map.c ./traprain-common/place.c ./traprain-common/route.c ./traprain-common/routing-request.c ./traprain-common/uri.c ./traprain-common/languages-map.h ./traprain-common/place.h ./traprain-common/route.h ./traprain-common/routing-request.h ./traprain-guidance/turn-by-turn-service.c ./traprain-guidance/turn-by-turn-notification.c ./traprain-guidance/turn-by-turn-service.h ./traprain-guidance/turn-by-turn-notification.h --c-include-directories /home/user/Documents/tmp/traprain /home/user/Documents/tmp/traprain --pkg-config-packages glib-2.0 gio-2.0 --gi-sources traprain-common/TraprainCommon-0.gir traprain-service/TraprainService-0.gir traprain-client/TraprainClient-0.gir traprain-guidance/TraprainGuidance-0.gir --gi-smart-index --gi-index traprain-overview.markdown --dbus-sources ./dbus/org.apertis.Navigation1.Routes.xml ./dbus/org.apertis.Navigation1.Route.xml ./dbus/org.apertis.Traprain1.Mock.xml ./dbus/org.apertis.NavigationGuidance1.Progress.xml ./dbus/org.apertis.NavigationGuidance1.TurnByTurn.xml  --dbus-smart-index --devhelp-activate  run --deps-file-dest ./.hotdoc.d/traprain-0.d --deps-file-target HOTDOC-traprain_0.stamp; touch HOTDOC-traprain_0.stamp ;
WARNING: [core]: (gtk-doc-bad-link): /home/user/Documents/tmp/traprain/traprain-common/routing-request.c:228:49: Trying to link to non-existing symbol ‘TrpPlace’
00226: * @self: a routing parameter
00227: *
00228: * If this routing parameter could represent a #TrpPlace, return it. Otherwise,
                                                     ^
00229: * return %NULL.
00230: *
```

**Comment by MathieuDuponchelle** [comment] 2016-11-14 21:03
Can't reproduce on my end, this must have something to do with the package in Apertis. Here is the output in a fresh virtual environment, using hotdoc 0.8.1 from pip:

https://gist.github.com/MathieuDuponchelle/58048c67fb222924adecf994135d7f9c

This does not happen with the latest version either.

Not closing as I'm willing to help you investigate the issue, but please first try to get hotdoc from pip and see whether it does work better on your end as well.

**Closed** 2016-11-16 20:32 UTC
Labels: needinfo

**Comment by MathieuDuponchelle** [comment] 2016-11-16 20:37
Sorry, I had missed the second part of your steps, thanks for the report :)

**Comment by Thread974** [comment] 2016-11-17 05:48
I have tested it, no more warning :+1:
